Turn SearchType variable into an int
NyaaPantsu/nyaa pull request #1371
Opened 2017-08-14 06:19 UTC by Kiloutre

not that it matters much but heh

2017-08-20 21:40 UTC, akuma06 requested changes

2017-08-20 21:40 UTC, akuma06 commented on controllers/search/search.go
> +	searchForm.SortType, err = strconv.Atoi(c.Query("sort"))
Move this to https://github.com/NyaaPantsu/nyaa/pull/1371/files#diff-2ff0b4807eadb9a31e1e7b187f5da802R50
It's better to have it directly set in the NewSearchForm function

2017-08-22 00:22 UTC, Kiloutre commented on controllers/search/search.go
> +	searchForm.SortType, err = strconv.Atoi(c.Query("sort"))
order & sort are not related to the search results nor form but only to the refine form, more precisely only to show the correct value in the two \<select\> after a page load which is just a display thing, so putting it right under the refine bool which is also just a display thing (display refine form yes/no) seems to make sense to me

2017-08-22 19:16 UTC, akuma06 commented on controllers/search/search.go
> +	searchForm.SortType, err = strconv.Atoi(c.Query("sort"))
It's not that, NewSearchForm have an argument with c *gin.Context. This function should provide a default SearchForm based on the values passed by c.
Except for refine which I agree should be set in SearchHandler, I would like order&sortType to be set in NewSearchForm. The reason is that I would like to reuse the SearchForm for things beside the Search pages (for example, in mod panel for listing pages).
Therefore, in order to not copy/paste multiple times the lines for "order" and "SortType", having them directly in NewSearchForm is better.

2017-08-22 20:57 UTC, Kiloutre commented on controllers/search/search.go
> +	searchForm.SortType, err = strconv.Atoi(c.Query("sort"))
alright but i already tried making the changes you requested and i miserably failed at it so i can't really do it anyway

2017-08-25 11:15 UTC, closed without merging